---

- name: "SECTION | 3.1 | Disable unused network protocols and devices"
  include: cis_3.1.x.yml

- name: "SECTION | 3.2 | Network Parameters (Host Only)"
  include: cis_3.2.x.yml

- name: "SECTION | 3.3 | Network Parameters (Host and Router)"
  include: cis_3.3.x.yml

- name: "SECTION | 3.4 | Uncommon Network Protocols"
  include: cis_3.4.x.yml

- name: "SECTION | 3.5.1 | Configure firewalld"
  include_tasks: cis_3.5.1.x.yml
  when:
      - rhel7cis_firewall == "firewalld"
  tags:
      - firewalld

- name: "SECTION | 3.5.2 | Configure nftables"
  include_tasks: cis_3.5.2.x.yml
  when:
      - rhel7cis_firewall == "nftables"
  tags:
      - nftables

- name: "SECTION | 3.5.3.x.x | Configure iptables"
  block:
      - name: "SECTION | 3.5.3.1.x | Configure iptables"
        include_tasks: cis_3.5.3.1.x.yml
      - name: "SECTION | 3.5.3.2.x | Configure iptables"
        include_tasks: cis_3.5.3.2.x.yml
  when:
      - rhel7cis_firewall == "iptables"
  tags:
      - iptables

- name: "SECTION | 3.5.3.3.x | Configure ip6tables"
  include_tasks: cis_3.5.3.3.x.yml
  when:
      - not rhel7cis_ipv6_required
      - rhel7cis_firewall == "iptables"
  tags:
      - iptables
      - ip6tables
