---

- name: Tooling configuration for rhel7-cis hardeling 
  hosts: all
  become: true
  become_method: sudo
  gather_facts: true

- name: Set ANSIBLE_PYTHON_PATH
  become: yes
  environment:
    name: ANSIBLE_PYTHON_PATH
    value: /usr/bin/python3.9


  #vars_files:
  # - .rhel_ec2_cis.yml


  tasks:
    - name: CIS Hardening
      include_role:
        name: rhel7_cis
